baseurl="https://rizasal.github.io"
languageCode = "en-us"
title="Riza Sal"
theme="archie-custom"
copyright = "© Riza S"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname="rizasal-github-io"
googleAnalytics="UA-176593761-1"

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	subtitle = "All things programming"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rizasal"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/_riza_sal"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/riza_sal"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4